### ISSUE TITLE
Search isn't working

### ISSUE THREAD

**Issue by o2rhkzqx** [DJDoubleD/QobuzDownloaderX-MOD#1]
**Describe the bug**
Search option is giving no response, just a blank screen

**To Reproduce**
1. Go to "Open Search"
2. Type your query
3. Click on Search
4. No result display

**Expected behavior**
The search option must populate the screen with all the relevant matches like track, album, artist, etc.

**Screenshots**
![image](https://user-images.githubusercontent.com/104969742/232250960-238afc17-fb8e-4f76-bdf8-4745b11c0528.png)

**Additional context**
NA

**Comment by DJDoubleD** [comment]
I'm not able to reproduce this issue. I'm assuming the steps taken were:

1. login to app
2. click "open search" button
3. select "track" in search type dropdown (derived from screenshot)
4. click in search field
5. type "faded" as querry
6. press either "enter" or click "search" button

When I follow the same steps, the search results are populated:
![image](https://user-images.githubusercontent.com/34967020/232252849-19df98f9-1153-460e-9b98-75a9e87fdc10.png)

Is there any other info you can provide?
I can only test on windows 10 unfortunately.

**Comment by DJDoubleD** [comment]
Problem is most likely due to not using user_auth_token in search.
Will add user authentication in each search.

**Comment by o2rhkzqx** [comment]
I am using Windows 11.
Will check it again once you update it as you said to add user auth in each search.
