### ISSUE TITLE
Any difference with genuine QBZ file ?

### ISSUE THREAD

**Issue by Lezardon** [DJDoubleD/QobuzDownloaderX-MOD#104]
Hello

I would like to know if the downloaded files have any difference in term of quality with the genuine files from Qobuz ?

thank you

**Comment by DJDoubleD** [comment]
@Lezardon The very first line in my project's description answers your question:

>Downloads streams directly from Qobuz.

So no, there is no difference in quality as the downloaded files **_are_** the genuine files that Qobuz streams in their own web player.
