### ISSUE TITLE
[Bug] FAILED API REQUEST unable to login

### ISSUE THREAD

**Issue by MikevE1995** [DJDoubleD/QobuzDownloaderX-MOD#107]
# **🐞 Bug Report**

## **Describe the bug**

Unable to login: failed API request

---

### **Is this a regression?**

Worked fine before on the same version

---

### **To Reproduce**

When trying to login you get a login failed notification. This happens with multiple login credentials.

---

### **Expected behaviour**

/

---

### **Screenshots**

LOGS:

Failed API request: 
Method: GET, RequestUri: 'https://www.qobuz.com/api.json/0.2/user/login?user_id=2709472&user_auth_token=BYq_BLvGf5t6BPAI_cOz2oJWB1e8LVRYuYeLr4gADcvoVVpUxAo62Mu9ZZMp7iDrkPv31wzp2SkM7IqQ9sOvAA', Version: 1.1, Content: <null>, Headers:
{
  User-Agent: Mozilla/5.0
  User-Agent: (Windows NT 10.0; Win64; x64; rv:109.0)
  User-Agent: Gecko/20100101
  User-Agent: Firefox/110.0
  X-App-Id: 579939560
}
Api response code: 401
Api response status: error
Api response reason: Invalid username/email and password combination
Failed API request: 
Method: GET, RequestUri: 'https://www.qobuz.com/api.json/0.2/user/login?user_id=1554159&user_auth_token=Qw1-n9Z-eMq4SvdEj3CP0JYLY13qgA4Xfga1HLNbJn32ePUWcOXSDa6UJeQ3dld5zogre7ME1rmZRm6GNOxw5g', Version: 1.1, Content: <null>, Headers:
{
  User-Agent: Mozilla/5.0
  User-Agent: (Windows NT 10.0; Win64; x64; rv:109.0)
  User-Agent: Gecko/20100101
  User-Agent: Firefox/110.0
  X-App-Id: 579939560
}
Api response code: 401
Api response status: error
Api response reason: Invalid username/email and password combination
Failed API request: 
Method: GET, RequestUri: 'https://www.qobuz.com/api.json/0.2/user/login?user_id=2709472&user_auth_token=BYq_BLvGf5t6BPAI_cOz2oJWB1e8LVRYuYeLr4gADcvoVVpUxAo62Mu9ZZMp7iDrkPv31wzp2SkM7IqQ9sOvAA', Version: 1.1, Content: <null>, Headers:
{
  User-Agent: Mozilla/5.0
  User-Agent: (Windows NT 10.0; Win64; x64; rv:109.0)
  User-Agent: Gecko/20100101
  User-Agent: Firefox/110.0
  X-App-Id: 579939560
}
Api response code: 401
Api response status: error
Api response reason: Invalid username/email and password combination

---

### **Additional context**

My friend has the exact same issue

**Comment by MikevE1995** [comment]
@DJDoubleD thanks for the quick response!

Im not surprised, Qobuz has been changing a lot lately. I will patiently wait for the new update.

Thanks in advance!

**Comment by MikevE1995** [comment]
@DJDoubleD I have installed the new version but am not sure how to get the old app id and app secret?

The login from Firehawk still aren't working, so I assume I need to get the old app id and secret, just not sure how to get that?

**Comment by HeavenlyGlory** [comment]
Login help

Does the id/token from my browser go into AppId and AppSecret values?

**Comment by DJDoubleD** [comment]
> Does the id/token from my browser go into AppId and AppSecret values?

No, when logging in the normal way, with email + password, don't worry about the AppId and AppSecret and leave the settings blank. QobuzDownloaderX-MOD will automatically get the AppId and AppSecret on each login (like before).

When logging in the alternative way, using ID + Token, you still press the `Can't log in? Click here` label to switch the login fields to ID and Token and you enter your id/token in the dedicated login fields, just like before.
Only if the login fails with (in error log) error code `401 - Invalid username/email and password`, you can change the AppId and AppSecret to the values that correspond to the ones with which your token was created in the new settings screen.
You only need to enter these once, the application will save them.

Should you get a new account and fetch a fresh user id and token using [one of the methods described in my wiki,](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/wiki/Logging-In-(The-Alternate-Way)) you'll have to clear the fields in the settings screen before logging in with the new id/token, to let the application fetch the most recent values itself.

I'm not going to directly publish any AppIds or Secrets on github (see my disclaimer in ReadMe), but you'll probably find what you are looking for [here](https://telegra.ph/How-to-fix-403---Invalid-usernameemail-and-password-10-12)
