### ISSUE TITLE
[Feature Request] DSD and DXD Downloads

### ISSUE THREAD

**Issue by kpayne182** [DJDoubleD/QobuzDownloaderX-MOD#108]
# **🚀 Feature Request**

Qobuz just announced DSD and DXD downloads!!! Any chance these will be added for download?

https://www.qobuz.com/us-en/quality/DSD-1-bit/download-streaming-albums

https://www.qobuz.com/us-en/quality/HD-24-bit/download-streaming-albums?ssf%5BsortBy%5D=main_catalog_date_desc&ssf%5Bdx%5D=1

**Comment by DJDoubleD** [comment]
In short: no.

The Qobuz [press release](https://community.qobuz.com/press-en/wkzevd37g3vue6pvs4anu3j1kcs74f-835ww) clearly states they added the formats to their **_download_** platform, not their **_streaming_** platform.
QobuzDownloaderX-MOD can only download streamable tracks and formats.

**Comment by kpayne182** [comment]
> In short: no.
> 
> The Qobuz [press release](https://community.qobuz.com/press-en/wkzevd37g3vue6pvs4anu3j1kcs74f-835ww) clearly states they added the formats to their **_download_** platform, not their **_streaming_** platform. QobuzDownloaderX-MOD can only download streamable tracks and formats.

Yea was hoping for a workaround. Hopefully the go to download for dsd as well.
