### ISSUE TITLE
Buy Me A Coffee link?

### ISSUE THREAD

**Issue by MikevE1995** [DJDoubleD/QobuzDownloaderX-MOD#109]
@DJDoubleD do you have a way to financially support you, like 'Buy Me A Coffee'?

**Comment by DJDoubleD** [comment]
Thank you for your consideration, but I do not have any means to accept donations and I'm not really planning on setting any up.
So feel free to spend the money you intended to donate to go out and buy yourself a coffee (or beer ;) ) and drink to all our health :)
