### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by Darkil1** [DJDoubleD/QobuzDownloaderX-MOD#111]
Hi, I wonder if downloading songs in DSD format will be implemented? The platform has recently added albums with DSD 64 resolution to the platform

**Comment by DJDoubleD** [comment]
DSD is currently only added on Qobuz for a select number of albums as Purchase Only option.
If they ever introduce DSD streaming (which is highly unlikely), it might be possible.
Until then, no: only streamable formats can be downloaded.
