### ISSUE TITLE
Can't log in anymore

### ISSUE THREAD

**Issue by iamlight33** [DJDoubleD/QobuzDownloaderX-MOD#112]
Hi! 

For months, everything was working fine in QBDLX-MOD & QBDLX, 
but now no ID / Token combinations are working for me neither in 
QBDLX 1.0.0.2 nor QBDLX-MOD 1.2.5.0, 1.2.6.0, or 1.2.7.0.

This is the error code in QBDLX-MOD 1.2.6.0 / 1.2.7.0:

Api response code: 400
Api response status: error
Api response reason: Invalid or missing app_id parameter. 

This is the error code in QBDLX-MOD 1.2.5.0:

Api response code: 401
Api response status: error
Api response reason: Invalid username/email and password combination

This is the error code in QBDLX 1.0.0.2:

System.NullReferenceException: The object reference was not set to an object instance.
   bei QobuzDownloaderX.LoginForm.loginBackground_DoWork(Object sender, DoWorkEventArgs e)

I am using the user_id / user_auth_token log in, but it's not working anymore...

Please help! Thanks in advance!

**Comment by DJDoubleD** [comment]
Please search existing (open & closed) issues first before making a new one.
I'm pretty sure you'll find the answer [here](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/issues/107#issuecomment-2408629587)
