### ISSUE TITLE
[Bug] Cant login using a token

### ISSUE THREAD

**Issue by Myuui** [DJDoubleD/QobuzDownloaderX-MOD#113]
# **🐞 Bug Report**

## **Describe the bug**
While trying to login with token and user ID it fails to connect
here's the logs
Failed API request: 
Method: GET, RequestUri: 'https://www.qobuz.com/api.json/0.2/user/login?user_id=3279668&user_auth_token=iqmkIrF4yaSV9Cq8AP4V1zpOQfQfLrSnXIUQSCXxZIQMh8IEcdx1GrhP1tULE6mu33ljK1G5rmXSi7TIyKgAPw', Version: 1.1, Content: <null>, Headers:
{
  User-Agent: Mozilla/5.0
  User-Agent: (Windows NT 10.0; Win64; x64; rv:109.0)
  User-Agent: Gecko/20100101
  User-Agent: Firefox/110.0
  X-App-Id: 579939560
}
Api response code: 401
Api response status: error
Api response reason: Invalid username/email and password combination

*

---

### **Is this a regression?**
Tested on 1.2.6.0 and 1.2.7.0
---

### **To Reproduce**

Login using an auth id and token

---

### **Expected behaviour**

* enter the panel to rip

---

### **Screenshots**

![image](https://github.com/user-attachments/assets/c2f1385d-47b7-43f2-992b-17faf669126f)

---

### **Additional context**

*

**Comment by DJDoubleD** [comment]
Please search existing (open & closed) issues first before making a new one.
I'm pretty sure you'll find the answer [here](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/issues/107#issuecomment-2408629587)
