### ISSUE TITLE
[Bug] I can't login 

### ISSUE THREAD

**Issue by rudraksh-773** [DJDoubleD/QobuzDownloaderX-MOD#117]
as of now i was internet for a month , when i came back and tried downloading some songs , the downloader was not loggin in , i updated from 1.2.5.0 to 1.2.7.0 and also used a renewed token , but still the same error , its says "  getting app id and secret " then " found app secret and app id ... loggin in "  then Login Failed , i have tried through diferent tokens, reinstallation and network but still the same . 

![Screenshot 2024-11-14 230636](https://github.com/user-attachments/assets/b104bec8-c149-4412-9986-a9472ee78fd9)

Error Log 

Failed API request: 
Method: GET, RequestUri: 'https://www.qobuz.com/api.json/0.2/user/login?user_id=1554159&user_auth_token=Qw1-n9Z-eMq4SvdEj3CP0JYLY13qgA4Xfga1HLNbJn32ePUWcOXSDa6UJeQ3dld5zogre7ME1rmZRm6GNOxw5g', Version: 1.1, Content: <null>, Headers:
{
  User-Agent: Mozilla/5.0
  User-Agent: (Windows NT 10.0; Win64; x64; rv:109.0)
  User-Agent: Gecko/20100101
  User-Agent: Firefox/110.0
  X-App-Id: 579939560
}
Api response code: 401
Api response status: error
Api response reason: Invalid username/email and password combination

**Comment by DJDoubleD** [comment]
Please search existing (open & closed) issues first before making a new one.
The answer has been given before in https://github.com/DJDoubleD/QobuzDownloaderX-MOD/issues/107#issuecomment-2408629587

**Comment by DJDoubleD** [comment]
> but i have tried different Tokens and the issue presists

I am 100% certain that you did not manually enter the correct AppId & AppSecret in the login settings screen as the token you are using is generated for the old values, which the application cannot automatically fetch.
Please actually read the [comment](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/issues/107#issuecomment-2408629587) I linked to.
At the very end, there is a link to a telegra.ph page.
Just follow the instructions given...

**Comment by rudraksh-773** [comment]
Thanks man got it
