### ISSUE TITLE
Router issue with QBDLX

### ISSUE THREAD

**Issue by JLhot** [DJDoubleD/QobuzDownloaderX-MOD#119]
Hello,
I have a standard optical internet connection from a local provider. I use a wifi router delivered from the provider with a stock settings. I am unable co login to the QBDLX from neither LAN nor wifi. If I use my iPhone's 4G hotspot, I can login without any problems.

Can you please advise if there is any kind of network setting to check on the router configuration that needs to be enabled / disabled for the QBDLX to login properly? 

Thank you! Great App... 🙏🏻👍🏻

Kind regards, Jiri

**Comment by DJDoubleD** [comment]
I'm afraid there is no know solution for the problem you are facing.
It is known that Qobuz blocks IP's from accessing their API's and your test with the 4G hotspot has proven that your ISP assigned IP has been (temporarily?) blocked.

The only thing you can try, is to change your IP.
Easiest way is to try some free VPN services (e.g. Windscribe, Tunnelbear, ...) and test if you can connect that way.
If your internet package from your ISP includes multiple IP connections, you could try to either power cycle your modem or (if your router supports this) change the MAC address of your router and then reboot (ISP should assign it a new IP then).

This kind of IP block is purely on Qobuz's server side, as far as I know.

**Comment by JLhot** [comment]
Thank you DJDoubleD for your quick response. I have an update:
• i can login throuhg my Iphone hotspot
• if I change to the LAN aftar that I am able to use the app on the LAN
• even if i put the computer to sleep and keep the app opened… after wakeup the app still works on the LAN
• so the iPhone hotspot is ONLY needed to login to the app

**Comment by DJDoubleD** [comment]
> so the iPhone hotspot is ONLY needed to login to the app

This indicates that Qobuz might only put an IP ban/lock on the API endpoint for the login in certain situations.
There isn't much I can do about that, as if you close the app and restart it, the app will need to go through the login process in order to get the account (subscription) info/status.

I'm going to leave the issue open, just in case I ever decide to add a proxy feature.
But since the original version of the app is back in active development, I'm not sure the mod version is even needed anymore.

**Comment by JLhot** [comment]
Thank you DJDoubleD for your response. You can close this issue as I finally found that there is something sketchy with my ISP router. It doesn't really matter wether the connection comes from my iPhone or my optical internet. 8 out of 10 times it connects just fine, 2 times it reports error. Solution is just repeat the connection or restart the computer.
