### ISSUE TITLE
[Bug] actually this maybe not a bug,but confuse me

### ISSUE THREAD

**Issue by jasonwilliam12580** [DJDoubleD/QobuzDownloaderX-MOD#122]
I have always had a question that I don't understand. When downloading qobuz albums from qbdlx, if there are "album only" tracks in the album, it is generally not suitable for streaming and cannot be downloaded. However, if the entire album is "album only", it can be downloaded. What could be the reason?

**Comment by DJDoubleD** [comment]
I would expect the same as you describe.
Could you please include the link to an example album that is shown as "album only" but can be downloaded?

**Comment by jasonwilliam12580** [comment]
> for example: Transformers: Dark of the Moon - The Album https://www.qobuz.com/us-en/album/transformers-dark-of-the-moon-the-album-various-artists/0093624955429 The album only tracks in this album cannot be downloaded.
> 
> Mellow Medicine https://www.qobuz.com/us-en/album/mellow-medicine-naoko-gushima/hqddlcvrjr8cc This album is shown as album only, but all can be downloaded.
> 
> The above are just examples.In other similar albums mixed with album only tracks, the album only tracks cannot be downloaded, but albums containing all album only tracks can be downloaded.

**Comment by orbittwz** [comment]
It makes sense, if an album cannot be bought and you can stream it, you can download it via streaming.
Just like the 2nd link you posted.
If an album can be bought and there are several tracks which are "album only", it means you can't stream the tracks and those must be bought.

**Comment by DJDoubleD** [comment]
> It makes sense, if an album cannot be bought and you can stream it, you can download it via streaming. Just like the 2nd link you posted. If an album can be bought and there are several tracks which are "album only", it means you can't stream the tracks and those must be bought.

@jasonwilliam12580 This is actually the correct answer.
The real indication if a track or album can be downloaded, is if it's available for streaming.
Your example: Mellow Medicine https://www.qobuz.com/us-en/album/mellow-medicine-naoko-gushima/hqddlcvrjr8cc seems to me like an album that cannot be purchased in the Qobuz store, but it is available for streaming, so it can be downloaded.

To get the best results, either use the build in search feature or get a (free) Qobuz account and search on play.qobuz.com.
There "album only" isn't a thing (as far as I know) but you'll clearly see which albums/tracks are streamable.
Only those can be downloaded.
