### ISSUE TITLE
[Bug] Label download process stuck on one not downloadable album.

### ISSUE THREAD

**Issue by musicisgreat** [DJDoubleD/QobuzDownloaderX-MOD#25]
# **🐞 Bug Report**

Label download process stuck on one not downloadable album.

## **Describe the bug**

The bug is the following: when downloading an entire label, everything is doing fine until one album has "failed to parse API response for this type of album".  Now the download process is stuck on this one album, instead of continuing the other albums.

---

### **Expected behaviour**

When downloading labels there should be a function to skip this particular album (the one that's not downloading), so the rest of the albums from the label download can be downloaded properly! because I cannot find a way to say to the program to skip this album and to continue with the following ones. 

### **Screenshots**

---

### **Additional context**

* thanks in advance, amazing program you've produced!

**Comment by DJDoubleD** [comment]
@musicisgreat Can you please add the label link and the album link for the album that failed so I can try to reproduce this problem?

**Comment by musicisgreat** [comment]
Thank you for the quick response. It's quite a big label: https://play.qobuz.com/label/6286  (CPO label). I've tried different tokens, but no luck. To clarify, I don't mind if one album from the entire label cannot be downloaded. The problem is that when such album occurs, it's stating: 

Starting Downloads...

"Failed to parse API response for type Album. Details saved to error log"

The album that is causing this differs, but now (after several tries) the album is this one: https://www.qobuz.com/us-en/album/cantatas-for-the-hanoverian-kings-of-england-ira-hochman-barockwerk-hamburg-dominik-worner-hanna-zumsande/ffx2i9kb0my2a   . 

Another thing I noticed is that the folder structure is not optimal. is it possible in the future that the subfolders stating the resolution (" FLAC (16bit-44.1kHz)" and) for example, can be left out or be merged into one folder?

**Comment by DJDoubleD** [comment]
For the folder structure, there is already another existing ticket #24.

**Comment by musicisgreat** [comment]
hi, 
I see, have you been able to take a look at the problem?  thanks in advance.

**Comment by musicisgreat** [comment]
Hello,
 I've spotted you changed and added some code (cool!) . Since I am an nitwit in coding., please tell me what I have to do in order to implement you're changes!

**Comment by DJDoubleD** [comment]
> Hello, I've spotted you changed and added some code (cool!) . Since I am an nitwit in coding., please tell me what I have to do in order to implement you're changes!

You just have to wait until I build and release a new version with the implemented changes. When a new release is available, the app will show a notification upon launch.

**Comment by musicisgreat** [comment]
Thank you for the effort to make a new release. I like the fact that you implemented the log folder and the changes for label downloads. However, after trying to download the label again now with the new .1 version, the entire download quits now way too fast. Only 2 albums have been checked/downloaded. its ending in like 10 seconds with :
 " Download job completed with warnings and/or errors! Some or all files could be missing! "

When trying another label, it appears as if the program only downloads the first 2 album. after that it's either the previous mentioned error or it's just finished (while its missing like 100 albums) , stating 'Download job completed! All downloaded files will be located in your chosen path." 

if you have the time, please take a look again!

**Comment by DJDoubleD** [comment]
Yep, stupid mistake 😞 : left in a hard coded limit of 2 albums per label that I used for testing.
Limit is removed again in new release.

**Comment by musicisgreat** [comment]
You're the man! many thanks for all these quick adjustments ! everything works like a charm now :):)
