### ISSUE TITLE
[Bug] Goodies fail to download

### ISSUE THREAD

**Issue by Goldmaster** [DJDoubleD/QobuzDownloaderX-MOD#26]
# **🐞 Bug Report**

## **Describe the bug**

* Goodies such as pdf booklets do not download.

---

### **Is this a regression?**

I have tried a couple of times but seam to fail

### **Error Message**

```
Goodies found, downloading...Failed to download (First Phase). Error information below.

System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at QobuzDownloaderX.QobuzDownloaderX.DownloadAlbum(Album qobuzAlbum, String basePath, Boolean loadTracks, String albumPathSuffix)
   at QobuzDownloaderX.QobuzDownloaderX.DownloadAlbumBG_DoWork(Object sender, DoWorkEventArgs e)
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---
```

---

### **Expected behaviour**

* Have a pdf booklet along with the music tracks.

---

### **Screenshots**

---

### **Additional context**

*

**Comment by DJDoubleD** [comment]
Error is probably due to HTTP time-out during large digital booklet download. Default time-out for HTTP requests seems to be 100 seconds. Will try setting allowed time-out to 30 minutes and see if problem persists.

**Comment by Goldmaster** [comment]
Thank you

Don't see any option for any such setting

**Comment by DJDoubleD** [comment]
After more testing, I think there were some problems on Qobuz's side, causing the time-out's.
Error handling in general and of digital booklets in specific has been improved in the latest release.

I'm closing the issue for the time being. Feel free to re-open the issue if it persists in the latest release (please include error logs).
