### ISSUE TITLE
[Enhancement] Adding the release release date to the search result instead of the release release year.

### ISSUE THREAD

**Issue by IgorO25** [DJDoubleD/QobuzDownloaderX-MOD#30]
# **🚀 Enhancement Request**

## **Is your enhancement request related to a problem? Please describe.**

* Can you add the release date to the search result instead of the release year?

---

## **Describe the solution you'd like**

* For example, today's release: 19.05.2023.

---

## **Describe alternatives you've considered**

*

---

### **Additional context**

*

**Comment by DJDoubleD** [comment]
Opting for a more international format of YYYY-MM-DD
