### ISSUE TITLE
[Bug] Error when a link has more than 500 tracks

### ISSUE THREAD

**Issue by urbancosmos** [DJDoubleD/QobuzDownloaderX-MOD#32]
# **🐞 Bug Report**

## **Describe the bug**

* When I tried to download a link that includes more than 500 tracks, the program only download the first 500 tracks, and then stops with this error:

Album Download Task ERROR.
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at QobuzDownloaderX.Shared.DownloadManager.<DownloadAlbumAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at QobuzDownloaderX.Shared.DownloadManager.<StartDownloadAlbumTaskAsync>d__35.MoveNext()

---

### **Is this a regression?**
 NO

---

### **To Reproduce**

1.
2.
3.
4.

---

### **Expected behaviour**

* To download all the tracks that a links contains.

---

### **Screenshots**

---

### **Additional context**

*

**Comment by DJDoubleD** [comment]
The fixed limit of 500 items per link is currently a know limitation (that was also present in the original QBDLX) 1 API call only returns 500 items and I haven't implemented pagination to get the next 500 items from the API (until all items are fetched).
But even though the fixed limit of 500 items in known, there shouldn't be an error at the end.
Can you please include the link for which you encountered the error in this issue so I can investigate.

**Comment by urbancosmos** [comment]
Hi, here is the link:

https://www.qobuz.com/us-en/album/the-complete-stevie-wonder-stevie-wonder/vt8biuxonts9b

Thanks.
