### ISSUE TITLE
From original - suggestions to add

### ISSUE THREAD

**Issue by orbittwz** [DJDoubleD/QobuzDownloaderX-MOD#34]
Hey!
I'm so glad someone has raise the glove and took this project continuing this!!
Wanted to do so myself, just couldn't because I don't have time now...
Anyways, thank you very much first of all and I hope this will be amazing project!
Can I add this issue I opened in the original page:
https://github.com/ImAiiR/QobuzDownloaderX/issues/133

There are many suggestions and issues in this thread, and if you could take a look and let me know...
Thanks 😄

**Comment by orbittwz** [comment]
been one month, I hope you are working on this??

**Comment by nadeoki** [comment]
Looks like it's not gonna happen :(

**Comment by orbittwz** [comment]
it's not, but some were added... closing and opening a new updated thread.
