### ISSUE TITLE
[Enhancement] Please could you add this Tags? MEDIA, RELEASEDATE & URL

### ISSUE THREAD

**Issue by rodfeli** [DJDoubleD/QobuzDownloaderX-MOD#41]
# **🚀 Enhancement Request**

## **Is your enhancement request related to a problem? Please describe.**

Would be nice you include this missing extended tags MEDIA, RELEASEDATE, URL

---

## **Describe the solution you'd like**

Would be nice you include this missing extended tags. I think there are available from Qobuz:
* **MEDIA** (generally is "Digital Media")
* **RELEASEDATE** in the form of "YYYY-MM-DD" (I think it is great replacement for the actual "ORIGINALRELEASETIME" tag)
* **URL** (The link provided in **_Qobuz Link_** to snatch the album) - Maybe this one added as choice in the **_Tags to Save_**

**Comment by MikevE1995** [comment]
Release date tag used to work for me. It's only since the latest update that the release date only shows the year

**Comment by MikevE1995** [comment]
I would love to have the release date with not just the year

**Comment by rodfeli** [comment]
> I would love to have the release date with not just the year

Yes, the new release broken that. Before that the release date was fine and equal to the YEAR tag. I think the correct is mantain the YEAR tag as YYYY and the extended RELEASEDATE tag like YYYY-MM-YY as I mention in my Enhancement request.

**Comment by MikevE1995** [comment]
for me it currently is YYYY for both the release date and year tags

**Comment by rodfeli** [comment]
Yes,
the year in format YYYY is in both tags YEAR & ORIGINALRELEASETIME...

**Comment by DJDoubleD** [comment]
For my own reference:

- **RELEASEDATE**
The whole dates discussion was handled in #42
So this tag won't be added.

- MEDIA (generally is "Digital Media")
This seems to come directly from [MusicBrainz Picard's mapping](https://picard-docs.musicbrainz.org/en/appendices/tag_mapping.html#id14)
In the official [Vorbis Comment Specification](https://xiph.org/vorbis/doc/v-comment.html), this field isn't listed and in the officially [proposed update](https://wiki.xiph.org/Field_names), the field `SOURCEMEDIA` is proposed.
Given the fact that the naming is unclear, neither MediaInfo nor MP3Tag seem to use any of these tags and the value would be a hard coded 'Digital Media", I don't really see the added value to clutter the embedded tags with this.
I'll leave this one up to users to add in bulk afterwards with tools like MusicBrainz Picard or MP3Tag if they so wish.
So this tag won't be added.

- URL
This seems like a useful tag to add, even though it's not listed anywhere as an official Vorbis Comment field, several players and tools I've tested seem to recognize and use the URL field for FLAC files.
For MP3 files, I think I'll probably use the [WCOM](https://mutagen-specs.readthedocs.io/en/latest/id3/id3v2.4.0-frames.html#url-link-frames-details) ID3 v2.4 Frame.
When I get to it, I'll add this tag to the options so the users can decide if they want it written to the files or not.
The link used will be the album URL that the Qobuz API returns for each track/album. This url links to the Album in the Qobuz store and seems most consistent.

**Comment by rodfeli** [comment]
> For my own reference:
> 
> * **RELEASEDATE**
>   The whole dates discussion was handled in [[Enhancement] Release date tag only shows the year #42](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/issues/42)
>   So this tag won't be added.
> * MEDIA (generally is "Digital Media")
>   This seems to come directly from [MusicBrainz Picard's mapping](https://picard-docs.musicbrainz.org/en/appendices/tag_mapping.html#id14)
>   In the official [Vorbis Comment Specification](https://xiph.org/vorbis/doc/v-comment.html), this field isn't listed and in the officially [proposed update](https://wiki.xiph.org/Field_names), the field `SOURCEMEDIA` is proposed.
>   Given the fact that the naming is unclear, neither MediaInfo nor MP3Tag seem to use any of these tags and the value would be a hard coded 'Digital Media", I don't really see the added value to clutter the embedded tags with this.
>   I'll leave this one up to users to add in bulk afterwards with tools like MusicBrainz Picard or MP3Tag if they so wish.
>   So this tag won't be added.
> * URL
>   This seems like a useful tag to add, even though it's not listed anywhere as an official Vorbis Comment field, several players and tools I've tested seem to recognize and use the URL field for FLAC files.
>   For MP3 files, I think I'll probably use the [WCOM](https://mutagen-specs.readthedocs.io/en/latest/id3/id3v2.4.0-frames.html#url-link-frames-details) ID3 v2.4 Frame.
>   When I get to it, I'll add this tag to the options so the users can decide if they want it written to the files or not.
>   The link used will be the album URL that the Qobuz API returns for each track/album. This url links to the Album in the Qobuz store and seems most consistent.

Hi [DJDoubleD](https://github.com/DJDoubleD),

It seems the ReleaseDate is not saved in the tag DATE, it is saved as a double YEAR tag (the year is also saved in this tag)

Thanks for adding the URL tag, improve the download speed and a great update for this gorgeous tool!!!

**Comment by MikevE1995** [comment]
For me the FLAC file release dates are correctly saved in the tag Date and Year

**Comment by rodfeli** [comment]
> For me the FLAC file release dates are correctly saved in the tag Date and Year

Not for me. I even deleted the configuration and reconfigured it in case any value in settings.json had been wrong

https://ptpimg.me/1ig8b6.jpg

**Comment by DJDoubleD** [comment]
> > For me the FLAC file release dates are correctly saved in the tag Date and Year
> 
> Not for me. I even deleted the configuration and reconfigured it in case any value in settings.json had been wrong
> 
> https://i.imgur.com/6dRVJLh.jpg

Most likely you are checking the tags with a program that just combines the YEAR and DATE tags and displays then as 1 field.
If you want completely correct info from a file, use something like [exiftool](https://exiftool.org/) to check all properties and tags as they are actually present in the file.
For me, the YEAR and DATE tags are correct:
![image](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/assets/34967020/eeee8a6e-e66e-4ff6-bf6e-9c57761fe5e0)

If you managed to download a FLAC file with both tags enabled and don't get separate Year and Date tags in the output from exiftool, I would be interested in the link and settings used. But I strongly suspect you will also get separate tags in the output from your files.

**Comment by rodfeli** [comment]
Yes! You are right! 
I really don't know if I added these lines a long time ago or it comes like this... but here is the problem.

https://i.imgur.com/LqrOJDR.jpg

All is fine DjD!

Thanks again for your great work!

**Comment by orbittwz** [comment]
this issue thread helped me understand the Year vorbis tag when using the program.
I was having issues when selecting the Release Year option instead of Release Date option...
The Year vorbis tag was showing YEAR all in upper case, and was considered custom field by some programs.
I chose Release Date option and it was fine, when running Exiftool the Date vorbis tag is used now, and it's considered not custom to most programs.
