### ISSUE TITLE
[Enhancement] Release date tag only shows the year

### ISSUE THREAD

**Issue by MikevE1995** [DJDoubleD/QobuzDownloaderX-MOD#42]
# **🐞 Bug Report**

## **Describe the bug**

Release date is not working properly. The file release date only shows the year and not the exact date. Right now 'Year' and 'Release date' both only show the year.

---

### **Is this a regression?**

I never used release date tag so wouldn't know.

---

### **To Reproduce**

1. check 'release date' in QobuzDownloaderX before downloading
2. Download album
3. Go to your FLAC file in Windows explorer
4. Go to 'details' and look for 'release date'

---

### **Expected behaviour**

The release date tag should say dd-mm-yyyy and not just the year.

---

### **Screenshots**

N/A

### **Additional context**

QobuzDownloaderX does say the correct release date on the right side while downloading. It's just the file itself that doesn't have it.

**Comment by DJDoubleD** [comment]
This was in fact a deliberate change to have consistency between the MP3 file tags and the FLAC file tags and having the year there was my personal preference (my application, my rules ;-p).
The complete date is currently written to the "ORIGINALRELEASETIME".

I'll look into the [ID3 v2.4 specs regarding dates](https://eyed3.readthedocs.io/en/latest/compliance.html) when I get the chance to see if I can find a good way to handle the dates and put the full date back in the "DATE" field.

**Comment by rodfeli** [comment]
Hi DJDoubleD,

I suggest the YEAR tag only has the release year here (in former releases - 1.2.1 and below - had the complete Release Date). 
The RELEASEDATE tag would be filled with the complete release date (now filled in a no common tag "ORIGINALRELEASETIME")
This is part of my suggestions in other post.

Thanks

**Comment by viviancels** [comment]
Hi. It better write XXXX-XX-XX format in YEAR tag. But problem is that ORIGINALRELEASETIME write XXXX-XX-XX format only in first track, in second and third tracks in ORIGINALRELEASETIME write only XXXX. https://i.postimg.cc/659YZ1d8/2023-08-16-092209.png

**Comment by MikevE1995** [comment]
Yesterday I manually changed the date and year tags which I know for a fact works with Plex:

tag 'date' to show YYYY-MM-DD
tag 'year' to show YYYY

**Comment by DJDoubleD** [comment]
> Yesterday I manually changed the date and year tags which I know for a fact works with Plex:
> 
> tag 'date' to show YYYY-MM-DD tag 'year' to show YYYY

As I [explained here](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/issues/43#issuecomment-1685408800) in #43, I'm inclined to implement this solution and separate the Release Date and Year completely to give the user maximal control.

The problem described by @viviancels:

> But problem is that ORIGINALRELEASETIME writes XXXX-XX-XX format only in first track, in second and third tracks in ORIGINALRELEASETIME writes only XXXX.

Is in fact a bug. The ORIGINALRELEASETIME tag was supposed to contain the Release Date in YYYY-MM-DD format for all tracks. This problem wil be resolved but by writing the full date to the DATE tag and the year only to the YEAR tag.
The ORIGINALRELEASETIME tag won't be used anymore.

**Comment by DJDoubleD** [comment]
To the contributors to this issue: @MikevE1995 @viviancels @rodfeli, could you please try out the test build attached to this comment (build version 1.2.3.1)?
This is a build that, with regards to this issue, separates the Release Date and Release Year completely (they have their own checkboxes to enable/disable writing either tag) and writes the date info as follows:

### For FLAC:
- Release Year: YYYY written to the Vorbis Comment "YEAR" field.
- Release Date: YYYY-MM-DD written to the Vorbis Comment "DATE" field.

### For MP3:
- Release Year: YYYY written to the ID3 v2.4 "TDRC" (recording date) Frame.
- Release Date: YYYY-MM-DD written to the ID3 v2.4 "TDRL" (release date) Frame.

This seems to stick as close as possible to the Vorbis Comment and ID3 v2.4 specs and works well in my testing.
I'm just asking if you wouldn't mind testing these changes.
Unless I get feedback that would indicate this solution breaks something (within a few days), I'll go ahead and make this an official release.
Thanks in advance for your cooperation.

[QBDLX-MOD_1.2.3.1.zip](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/files/12402409/QBDLX-MOD_1.2.3.1.zip)

**Comment by MikevE1995** [comment]
It's almost midnight overhere so will test it tomorrow morning. Could you also change the record label tag to 'label' instead of 'organization', or maybe use both tags? If you are able to change that today I will be able to test that out tomorrow too

**Comment by DJDoubleD** [comment]
> Could you also change the record label tag to 'label' instead of 'organization', or maybe use both tags?

I think I'm around the same timezone, so I'm done for today :-) (this is just a hobby...).

Regarding the label, as I explained at length in #43, the ORGANIZATION tag stays, as it is the official correct tag.
I could write the same info to the unofficial LABEL tag (only for FLAC) as well (and then hope nobody else starts complaining that they don't want that tag...).
Please update your request #43 to reflect this as an acceptable solution so I can keep track of things more easily (issues are bleeding into each other now...)

**Comment by MikevE1995** [comment]
I have just tested the new version and the year and release date tags both work great within Plex!

**Comment by rodfeli** [comment]
Hi [DJDoubleD](https://github.com/DJDoubleD),
After some tests the new version seems to work great with the date tags.
Both tags are in the (multitag) YEAR (with double seperator \\) as explained by [viviancels](https://github.com/viviancels) above.
Although in my opinion the best solution is that the complete date must to be written in the (extended, info) tag RELEASEDATE and the Year in the main tag YEAR. Anyway, now it works perfectly and if that's the way it's most compatible, it's great!
Thanks!!!
