### ISSUE TITLE
[Enhancement] Link the 'recordlabel' tag to 'label' and not 'organization'

### ISSUE THREAD

**Issue by MikevE1995** [DJDoubleD/QobuzDownloaderX-MOD#43]
# **🚀 Enhancement Request**

## **Is your enhancement request related to a problem? Please describe.**

Yes, currently the 'label' tag is linked to 'organization'.

---

## **Describe the solution you'd like**

Link the recordlabel to the 'label' tag instead of the 'organization' tag

---

## **Describe alternatives you've considered**

N/A

---

### **Additional context**

N/A

**Comment by DJDoubleD** [comment]
To see the actual tags in an audiofile, make sure to use an application like MP3Tag.
You would then see that the 'label' tag isn't written to the 'organization' tag, but to the 'publisher' tag for FLAC files.
This is per design with the reasoning for doing so explained in these [Release Notes](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/releases/tag/1.2.2.0), where I clearly stated:

- **_Label checkbox_**: write the record label to the Publisher tag to the audiofile.
The tag follows the [ID3 v2.4 standard](https://exiftool.org/TagNames/ID3.html) for Publisher.
Since the [Vorbis  Comment standard](https://xiph.org/vorbis/doc/v-comment.html) suggests the "ORGANIZATION" tag but most software seems to recognize the "PUBLISHER" tag, the Publisher tag is used in both MP3 and FLAC formats.

This was a deliberate decision so this won't be changed.

**Comment by MikevE1995** [comment]
I'm checking the albums in MusicBrainz Picard and it shows the recordlabel at the 'organization' tag. Plex isnt recognizing this organization tag so it doesn't show the record label

**Comment by DJDoubleD** [comment]
> I'm checking the albums in MusicBrainz Picard and it shows the recordlabel at the 'organization' tag. Plex isnt recognizing this organization tag so it doesn't show the record label

I double checked and I had an old mapping set in MP3Tag which automatically mapped the "ORGANIZATION" tag to the "PUBLISHER" tag for consistency, so I made a mistake there. It is in fact the "ORGANIZATION" tag being written to the FLAC files.
But even then, the [Vorbis  Comment standard](https://xiph.org/vorbis/doc/v-comment.html) states:
`ORGANIZATION
Name of the organization producing the track (i.e. the 'record label')`

Most software seems to handle the "ORGANIZATION" tag as expected, so it seems Plex isn't following the Vorbis Comment specs.
Nevertheless, I'll reopen the issue as a request to write the publisher to the unofficial "LABEL" tag in addition to the official "ORGANIZATION" tag (and I might merge it with another tags related request when I get to it).

@MikevE1995 : I don't have a plex server configured, Did you test that when you write the publisher to the "LABEL" tag for FLAC files, that Plex recognizes this tag? Also, could you maybe test a MP3 track and check if Plex reads the publisher from the ID3 tags as is? Thanks.

**Comment by MikevE1995** [comment]
I just did some tests and got some interesting results:

FLAC files link the recordlabel to 'organizations' tag.
MP3 files link the recordlabel to 'recordlabel' tag.

Neither of those worked for Plex so I tried to create the 'label' tag. This worked for the FLAC file but not for the MP3 file. The MP3 file automatically mapped 'label' to 'recordlabel'. On FLAC I was able to create a 'label' file which was the only one that showed in Plex.

**Comment by MikevE1995** [comment]
Today I have also noticed that the release date is not showed like YYYY-MM-DD but only as YYYY.

Maybe this could be fixed by using these tags:
tag 'date' to show the release date like YYYY-MM-DD
tag 'year' to show the release year like YYYY

**Comment by rodfeli** [comment]
> Today I have also noticed that the release date is not showed like YYYY-MM-DD but only as YYYY.
> 
> This could be fixed by using these tags:
> 
> tag 'date' to show the release date like YYYY-MM-DD tag 'year' to show the release year like YYYY
> 
> Would really appreciate if you could add this too while working on a fix for the issue above :). It's really appreciated!

Agreed.
Normally the Release Date is filled in a tag RELEASEDATE instead of only DATE tag.

**Comment by DJDoubleD** [comment]
> > Today I have also noticed that the release date is not showed like YYYY-MM-DD but only as YYYY.
> > This could be fixed by using these tags:
> > tag 'date' to show the release date like YYYY-MM-DD tag 'year' to show the release year like YYYY
> > Would really appreciate if you could add this too while working on a fix for the issue above :). It's really appreciated!
> 
> Agreed. Normally the Release Date is filled in a tag RELEASEDATE instead of only DATE tag.

After some reading and testing, I'm leaning towards using the YEAR and DATE tags for FLAC files as suggested by @MikevE1995.

For mp3 files, I found some more detailed info on the ID2 v2.4 Date Frames (tags) [here](https://eyed3.readthedocs.io/en/latest/compliance.html#id3-v2-4-date-frames). 
The library that is used to write all tags to the audio files ([taglib-sharp](https://github.com/mono/taglib-sharp)), supports the Year tag by default and seems to use the "TDRC" (recording date) Frame to write this to. 
MP3Tag also reads this "TDRC" Frame as Year.
Given this info and the fact that QBDLX has been using this Frame for the year in mp3's for several years now, I'm assuming this is correct and am not changing this.
The taglib-sharp library doesn't support a "date" tag by default, so I think I will be using the "TDRL" (release date) Frame to write the full release date to.

I'll probably need to create an extra checkbox to allow the user to enable/disable writing the Release Date tag separate from the Release Year.

But this discussion is actually related to #42, so it will be handled there.

Regarding the original request in this issue, it seems Plex simply doesn't read the correct Vorbis Comment field nor the correct ID3 frame for the Label/Publisher.
The official documentation from the [Vorbis  Comment standard](https://xiph.org/vorbis/doc/v-comment.html) confirms that ORGANIZATION is the correct field.
And the [ID3 v2.4 standard](https://exiftool.org/TagNames/ID3.html) lists the "TPUB" Frame as the correct field.
These are the fields which QBDLX-MOD currently already uses.

Barring clear evidence that the label should be written to an additional Vorbis Comment and/or ID3 v2.4 Frame, I'm inclined to handle the dates issue in #42 and simply close this issue and advice to ask the Plex team why their software doesn't use the standard metadata fields for the Label/Publisher in FLAC and mp3 files.

**Comment by MikevE1995** [comment]
Like you mentioned in the other post:

Writing the recordlabel info to both the 'label' and 'organization' tags for FLAC files is a good solution
