### ISSUE TITLE
Can't download albums 

### ISSUE THREAD

**Issue by limo31** [DJDoubleD/QobuzDownloaderX-MOD#5]
I do insert the link and choose the directory 
When i press download button i encounter the error ''API request failed for endpoint /album/get. Details saved to error log''

EDIT : nevermind i figured out

**Comment by limo31** [comment]
![qobuz](https://user-images.githubusercontent.com/130870526/232254620-90186677-7ecb-4cb1-805d-6ebb7bfd95f6.JPG)

**Comment by DJDoubleD** [comment]
Since you figured it out, I'm closing the issue. But for future reference, the error logs are saved in the folder with the binaries. Please include these logs in future bugreports
