### ISSUE TITLE
[Bug] Slash // in ARTIST and YEAR tags

### ISSUE THREAD

**Issue by marvellz** [DJDoubleD/QobuzDownloaderX-MOD#54]
I see this tag in the [Mp3tag](https://www.mp3tag.de/en/), and not all audio players understand this Artist tag because of the **//**. Only the first artist is displayed.

Maybe add a **comma** **,** or even an **&** between artists.

It is also better to leave only the **YY-MM-DD** format.

Example:

![Capture](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/assets/48913829/78c8b6ac-68c0-4244-a948-5fe9f3ed8c94)
![2](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/assets/48913829/204b35ae-168e-4fca-b873-07d093cc12d1)

**Comment by orbittwz** [comment]
For the artist field it's fine, your program doesn't know how it's displayed so it's adding slashes...
For the year field, you probably selected both "release date" and "release year" options in the program.
Remove one of them.
In any case, both field working as should and I strongly advice against this.

**Comment by marvellz** [comment]
@orbittwz , thx! Yes, I didn't notice that the audio player showed me **;**
I'm sorry.
