### ISSUE TITLE
[Feature Request]  Add censored label or any other way to know if an album is censored without having to downloading it

### ISSUE THREAD

**Issue by BenliM28** [DJDoubleD/QobuzDownloaderX-MOD#55]
![quesi copia](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/assets/91829837/4fcd5eda-e3ea-4d82-85eb-5d184ce63274)

**Comment by DJDoubleD** [comment]
Investigating if the "E" (Explicit) tag can easily be added to search results for this purpose. (dynamic layout is a pain in the @ss with winforms).
Just as reminder, the preview links to both the online player and the store site are an alternative way to find out the specific version without having to download the album/track.

**Comment by orbittwz** [comment]
As a quick workaround to omit this, usually, if not always, the Explicit label is visible on the cover of the album...
marked as "Parental Advisory Explicit Content"
If I can suggest something to this manner, I would enlarge the search results album covers and the whole window and the user would see if the albums are having those labels in the cover...
Cheers

**Comment by BenliM28** [comment]
Yeah I just realised that there’s an explicit label on the cover, it would help a lot if the image was bigger

**Comment by DJDoubleD** [comment]
As a solution Explicit Albums and Tracks will be Clearly indicated in the search results by an "E" label (with tooltip):

![QBDLX-Search-Explicit](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/assets/34967020/8681b3e3-9477-41da-9225-01a094c5adf7)

Example search string: "Thats What They All Say".

**Comment by orbittwz** [comment]
amazing!
