### ISSUE TITLE
[Feature Request]  Choose quality

### ISSUE THREAD

**Issue by Raprodent** [DJDoubleD/QobuzDownloaderX-MOD#64]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

* I'd like to be able to see different available qualities, or at least 'hone in' on one of them.

---

## **Describe the solution you'd like**

* Quality is displayed, could be listed as several options, selectable somehow.

---

## **Describe alternatives you've considered**

*

---

### **Additional context**

* Any way to DM you somewhere? I have more input that could be very relevant to quality :)

**Comment by orbittwz** [comment]
You have these options in the main window...
![image](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/assets/45605734/a518bd84-a782-4bc2-847c-003d21b3073e)
as shown, you can choose the max quality you want and the program will try to find the appropriate results.

**Comment by DJDoubleD** [comment]
> ## **Describe the solution you'd like**
> * Quality is displayed, could be listed as several options, selectable somehow.

As @orbittwz already pointed out, you can select the max download quality, just as you can in the Qobuz (web)player, so I don't really understand the question.

> * Any way to DM you somewhere? I have more input that could be very relevant to quality :)

That depends, I don't really see what kind of info you have that can't just be added here?

**Comment by DJDoubleD** [comment]
@Raprodent Can you please add your feedback as to why your request is not already covered by the existing quality selection options?
Without valid feedback, I'll just have to close this issue as invalid since there's nothing to be done about it...

**Comment by Raprodent** [comment]
Heya, sorry for being tardy on replying. Hope all is well.
You can close the topic. Still wondering if I can DM you somehow, I have some relevant questions on the topic, but not directly tied to this program. :)

**Comment by DJDoubleD** [comment]
@Raprodent 
> Still wondering if I can DM you somehow, I have some relevant questions on the topic, but not directly tied to this program. :)

I'm quite sure you'll find the answers to your questions in the following telegram channel: https://t.me/firehawk52_chat
