### ISSUE TITLE
You can change it when downloading to facilitate downloading again.

### ISSUE THREAD

**Issue by zjgmijg** [DJDoubleD/QobuzDownloaderX-MOD#66]
![image](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/assets/153508016/4bfac8fb-d5ea-4e58-b5e9-d24741277aa7)
When downloading, this can be made selectable and can be positioned with the mouse. In this way, enter can directly download again, which is very convenient.

As shown in the picture, the mouse can be positioned, so even if the card owner stops moving, I can enter and download directly.

**Comment by DJDoubleD** [comment]
I think you're trying to say that your download process sometimes stalls or "hangs" and you want to restart the download by resubmitting the download link (which is made read-only on purpose when a download task is running).
So I think that what you want is actually the same as #53.

Could you please confirm that I understood the problem correctly and you want to "cancel" a running download task that is stalled so you can restart it (in hopes that it won't stall anymore)?

**Comment by zjgmijg** [comment]
Yes, click Cancel STOP and it should stop immediately.
Then I start the download to prevent the card owner from

**Comment by orbittwz** [comment]
The current download cannot stop immediately since it's in the program queue thread and connection tunnel...
When it's finished the program stops the download.
Do you have like a slow connection, and because of it you are asking for instant stop?
That's the way programs work with connections...

**Comment by DJDoubleD** [comment]
I added the context of this issue to #53 and am closing this as a duplicate.
#53 will be used for future follow-up.
