### ISSUE TITLE
Issues Logging in

### ISSUE THREAD

**Issue by fettyluciano** [DJDoubleD/QobuzDownloaderX-MOD#67]
No amount of carefully entering the login credentials has allowed me to successfully log in. To be more certain that this issue may be with the program rather than a user error, I copied and pasted the ID and auth token from the exact same Notepad file into both the original QobuzDownloaderX and QobuzDownloaderX-MOD. While I successfully logged in with QobuzDownloader, I did not succeed with QobuzDownloaderX-MOD.

![Untitled](https://github.com/DJDoubleD/QobuzDownloaderX-MOD/assets/153741135/49d1efd3-68cd-4470-9dff-1a073c0b8d7e)

**Comment by orbittwz** [comment]
do you have some log file to post here?
