### ISSUE TITLE
[Question] Are downloads done over a secure connection?

### ISSUE THREAD

**Issue by MikevE1995** [DJDoubleD/QobuzDownloaderX-MOD#69]
Are downloads done by the programm via a HTTPS/SSL connection? I'm not even sure if this is even possible, but I was wondering if my ISP can see the data im downloading if I disable my VPN

**Comment by DJDoubleD** [comment]
The application doesn't force HTTPS connections for the downloads (for max compatibility) but in practice, I do think all downloads are effectively done over HTTPS.
The download URLs are fetched from the Qobuz API's, and in my experience, they currently always return HTTPS URLs for the streams.
The communication with the Qobuz APIs is also done through HTTPS links (see [Constants in QobuzAPISharp](https://github.com/DJDoubleD/QobuzApiSharp/blob/master/QobuzApiSharp/Api/QobuzApiConstants.cs)).

I hope this answers your question.
