### ISSUE TITLE
An unnecessary zero.

### ISSUE THREAD

**Issue by IgorO25** [DJDoubleD/QobuzDownloaderX-MOD#7]
An unnecessary zero.
Is it possible not to add an unnecessary zero in the tags of the track number? Was: "01", "02", etc., should be "1", "2", etc.

**Comment by IgorO25** [comment]
These are my preferences. Because of this, I unfortunately do not use your wonderful product, because there is additional work to remove zeros.

**Comment by DJDoubleD** [comment]
Since I did explicitly put "**Experimental**" in the project description and I personally also do prefer the clean numerical track numbering in the track metadata, I decided to implement the change and we'll just see what happens...
