### ISSUE TITLE
[BUG] Downloading albums with periods on the right side (and probably other special symbols) confuses the program

### ISSUE THREAD

**Issue by wyvern119** [DJDoubleD/QobuzDownloaderX-MOD#8]
It confuses the program whenever I downloaded an album with a period. Haven't tried downloading albums with special symbols, but it'll probably confuse it too.

Downloading Fiona Apple's When The Pawn... album recreates this issue. The program couldn't find the path because typing periods on the right side when renaming a folder automatically hides it.
![image](https://user-images.githubusercontent.com/60021836/232309347-af8ea04e-d3f7-4f8f-bb59-ac906858c7c5.png)

**Comment by wyvern119** [comment]
forgot to add this too
![image](https://user-images.githubusercontent.com/60021836/232309468-472dd59f-f99e-4493-a5ef-c3161209d971.png)
after renaming:
![image](https://user-images.githubusercontent.com/60021836/232309484-454f5bc5-3cd4-46fb-b538-3798944d37e5.png)

**Comment by Lixumos** [comment]
In Windows folders and files can't end with a dot... So maybe that's the issue

**Comment by DJDoubleD** [comment]
This is one of the remaining bugs which was inherited from the original version.

The [MSDN](https://learn.microsoft.com/nl-nl/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN) naming reccomendations state:

> Do not end a file or directory name with a space or a period.

So I'm just going to have the program remove all trailing periods from paths and filenames to fix this problem.
