### ISSUE TITLE
[Bug] It literally deleted all 1000+ songs i had downloaded on another folder on my pendrive

### ISSUE THREAD

**Issue by dani3400** [DJDoubleD/QobuzDownloaderX-MOD#80]
As stated in the title, i downloaded some songs on a pendrive on a completely different folder to have new songs, after i was done with that, i checked another folder with 1000+ songs on it to download some more songs but to that specific folder and i see literally nothing. I downloaded multiple apps that can recover lost files, and Recuva said that literally ALL of the songs were somehow magically replaced by the songs i downloaded on the other folder. I could not get a screenshot as i deleted the app since it didnt retrieve any of the songs, but i can 100% assure that somehow downloading songs with this app deleted 1000+ songs.

I dont want to recreate it, and the steps are as easy as just downloading songs and get unlucky i guess.
I dont know if its a rare chance issue that can happen with this app but either way, its just a bug i wanted to report.

**Comment by orbittwz** [comment]
that's unfortunate but afaik this program doesn't have delete actions in the code...

**Comment by dani3400** [comment]
i really dont know what could have caused it, Recove said all of those songs got "replaced" by the ones i downloaded, rn im using Disk Drill to see if i can at least recover the songs that were ripped from a cd. If i can do that at least and i cant recover the rest (which by the way there are songs missing that appeared in Recoverit but not on Disk Drill) i'll just probably redownload Recoverit and just download all of the songs individually because Disk Drill cant recover the name of the songs, it just says something like "file0000001" on some files.

**Comment by DJDoubleD** [comment]
I'm sorry this happened to you, but like @orbittwz already indicated, QobuzDownloaderX-MOD does not remove any files.
The app will only create folders and files in the specified download folder where it will explicitly check for and skip already existing files.

Did you actually check that the different folder which held the 1000+ tracks was still populated with the tracks **_before_** you started downloading the new tracks?

From your description, it seems like you only checked the existing folder **_after_** having downloaded additional tracks with QobuzDownloaderX-MOD, so the other songs might have already been removed **_before_** you started downloading (e.g. by not properly ejecting the drive last time you used it), and you only checked and noticed that they were gone **_after_** having downloaded the new tracks.

Btw, it is normal that file recovery apps will show that removed files were overridden with new files. That's just the way file systems work when writing to storage space that was previously occupied by removed files. That doesn't mean that the files were **_replaced_** by writing the new files, just that the new files were written to (a part of) the physical storage clusters that were previously occupied by the removed files.

If you actually explicitly checked the existing folder **_before_** starting the new download and verified that the files in it were there and playable, be aware that this incident might be an indication of the usb drive starting to fail.
These external media do have a limited lifespan and I have personally had multiple drives like that fail over time.
I would strongly recommend that you make a back-up of this drive if it contains only copies of files you do not want to lose...
