### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by DanniXDna** [DJDoubleD/QobuzDownloaderX-MOD#82]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

* I wish to have lyrics embed into my music.

---

## **Describe the solution you'd like**

* An implementation of lyrics to the songs from services like Musixmatch for synchronized lyrics or Genius for normal lyrics.
---

## **Describe alternatives you've considered**

* Other Lyrics services idk,

---

### **Additional context**

*

**Comment by orbittwz** [comment]
dupe of #63 ??

**Comment by DJDoubleD** [comment]
This is indeed a duplicate of #63.
I'll close this one and add a link to this issue in #63 just for reference.
