### ISSUE TITLE
Quick API question

### ISSUE THREAD

**Issue by Raprodent** [DJDoubleD/QobuzDownloaderX-MOD#83]
I an trying the API to get individual IDs displayed of tracks in a playlist via curl. Works with albums, but not displayed in the info returned for playlists for some reason. Since I'm not too code savvy I was thinking of asking how to either list those tracks or how it is worked around. 

Peyz

**Comment by DJDoubleD** [comment]
You didn't include the cURL cmd you tried for your playlist, but I'm guessing you need to add the parameter `&extra=track_ids` to your playlist request url.
See [my QobuzApiSharp docs](https://github.com/DJDoubleD/QobuzApiSharp/blob/master/docs/QobuzApiSharp.Service/QobuzApiService/GetPlaylist.md) & [code implementation](https://github.com/DJDoubleD/QobuzApiSharp/blob/master/QobuzApiSharp/Api/Service/Endpoints/QobuzApiService.Playlist.cs#L46) for reference
