### ISSUE TITLE
Only downloading 30 second samples[Bug] 

### ISSUE THREAD

**Issue by Whatisthisioi** [DJDoubleD/QobuzDownloaderX-MOD#88]
# **🐞 Bug Report**

## **Only downloading 30 second samples**
It was working fine before, but now It's only 30 seconds of the songs, I even tested songs I've already downloaded, but still only get the 30 sec samples.

**Comment by DJDoubleD** [comment]
Please use the search function first.
As already indicated multiple times (#57, #58, #59 & #73): this is not a bug. 
You are using an account without an active subscription, hence you only can access 30 second previews...
