### ISSUE TITLE
Result report

### ISSUE THREAD

**Issue by Lixumos** [DJDoubleD/QobuzDownloaderX-MOD#9]
After downloading is completed a report in the window could post if an album or a track failed/was skipped. So you can get it from some other source to get a complete discography.

**Comment by DJDoubleD** [comment]
I'm interpreting the question as adding the option to save or view the full output report that was shown on screen since the screen refreshes when starting a new album.

**Comment by Lixumos** [comment]
Exactly... just so you can see what was skipped after the amount of downloads is comple. It always shows "Downloading job completed! All downloaded files will be located in your chosen path." when completed. So any messages from you press download until completed is what I'm looking for
