### ISSUE TITLE
Need Support for Windows 8.1 !!!

### ISSUE THREAD

**Issue by Manupriyan** [DJDoubleD/QobuzDownloaderX-MOD#99]
# **🚀 Enhancement Request**

New update requires .Net framework 4.8.1 which can't be installed on windows 8.1 as it is not supported, which makes impossible to use/Download. Only .Net 4.8 can be installed. Could you make a way for windows 8.1 users.

Thanks
Manupriyan

**Comment by MxqingDesign** [comment]
Yes, I also think it should support Windows 7 and Windows 8.1 because they only support Net framework 4.8.

**Comment by orbittwz** [comment]
also the same as #102 , your OS is EOL and it doesn't make sense adapting and trying to fix the program to work with that.
please close the case and update to supported OSes.
